### PR TITLE
make Marklight processing pluggable

### PR DESCRIPTION
**Pull request by DivineDominion**
While the `MarklightTextStorage` subclass works nice, if you have another external `NSTextStorage` subclass already, you cannot combine the two. This PR attempts to minimize the work you need to perform in your `NSTextStorage` subclass through delegation to a `MarklightTextProcessor` service instead of through inheritance.

(Works a bit towards #8 already, putting the style configuration in the `MarklightTextProcessor` and out of the text storage, where a style object can be extracted from later.)

I am not 100% happy with the name of the types I came up with, especially `MarklightStyleApplier` as a protocol that takes the minimum from `NSMutableAttributesString`, intending to make writing test doubles easier.

### CODE REVIEW

**Comment by DivineDominion** [comment]
Found a problem I still have to fix: 

- [x] Typing in the first paragraph removes style of the following heading (only happens right after the start)

**Comment by DivineDominion** [comment]
@macteo fixed the problem. What do you think so far?

**Comment by macteo** [comment]
Seems good to me. 
I need to look at the code, but this can be probably be included in a new major version as there will be breaking APIs.

**Comment by DivineDominion** [comment]
I figured that won't be too much of a problem because it's 0.x anyway, but a 0.3 version jump makes sense to me. Tell me if I should increase it in the podspec and project settings.

**Comment by DivineDominion** [comment]
@macteo I finished an implementation for #6 based on this that's good to go 👍

**Pull request merged**
