### PR TITLE
macOS Framework (Work in Progress)

### PR DESCRIPTION
**Pull request by DivineDominion**
After the announcement in #5, here's the nearly finished macOS library version.

- [x] Test Carthage install
- [ ] Test CocoaPods install outside the sample project

I have performed a few changes. 

- Setex underlines are not hidden anymore, because that was super weird.
- Not using `removeWholeAttributes` anymore; that does not produce the same result as on iOS. 
- Not posting `edited` messages as often because they change the caret location on macOS.

## removeWholeAttributes() Problem

Here is the `removeWholeAttributes()` evidence :)

Before:

screen shot 2017-07-19 at 12 36 43

After typing, removing the styles:

screen shot 2017-07-19 at 12 37 15

### CODE REVIEW

**Comment by macteo** [comment]
Thanks for your great contribute.
To solve the travis issue you should probably change the iPhone SE id to `BA25BEF2-CAEF-4855-9BB3-63D0D6C4EEDD` in the *.travis.yml* configuration file.

The issue probably affects also the *develop* branch but as I don't have plans to make other commits there you can change it directly here.

**Comment by DivineDominion** [comment]
@macteo Thanks for the Travis-hint! 👍

I have found a way to re-style the edited paragraph and the surrounding ones to support Setext headings. So I think this is now identical to what it did before on iOS :)

Energy consumption is crazy high when typing, though. All the regular expressions are probably doing this. But that's an improvement for another PR. Could you give it a run and try to use it in a CocoaPods project to verify I did nothing wrong? As far as I'm concerned, the changes are merge-able.

**Comment by DivineDominion** [comment]
Ah, nearly forgot: If you want me to change the version in this PR to save you some work, just say so.

**Comment by macteo** [comment]
I'm gonna test CocoaPod as soon as possible, in the meantime please add yourself to the *Acknowledgements* if you like.

**Comment by macteo** [comment]
Feels good to me, as soon as it's merged I'm going to submit the CocoaPod update

**Comment by DivineDominion** [comment]
Sure, will do!

**Pull request merged**
